### ISSUE TITLE
Concurrent map write causes panic

### ISSUE THREAD

**Issue by knusbaum** [fhs/mux9p#3]
```
fatal error: concurrent map writes

https://github.com/fhs/mux9p

goroutine 148 [running]:
runtime.throw(0x43855ed, 0x15)
	/Users/kyle.nusbaum/sdk/go1.14.11/src/runtime/panic.go:1116 +0x72 fp=0xc000387d78 sp=0xc000387d48 pc=0x4034892
runtime.mapassign(0x431c160, 0xc000390030, 0xc000296598, 0x464b260)
	/Users/kyle.nusbaum/sdk/go1.14.11/src/runtime/map.go:585 +0x59d fp=0xc000387df8 sp=0xc000387d78 pc=0x4010c5d
github.com/fhs/mux9p.(*Config).conninthread(0xc000076000, 0xc0003a4000)
	/Users/kyle.nusbaum/go/pkg/mod/github.com/fhs/mux9p@v0.2.0/mux9p.go:240 +0x20f fp=0xc000387fd0 sp=0xc000387df8 pc=0x418597f
runtime.goexit()
	/Users/kyle.nusbaum/sdk/go1.14.11/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000387fd8 sp=0xc000387fd0 pc=0x4063b81
created by github.com/fhs/mux9p.(*Config).listenthread
	/Users/kyle.nusbaum/go/pkg/mod/github.com/fhs/mux9p@v0.2.0/mux9p.go:203 +0x4a
```

**Comment by fhs** [comment]
Thanks for reporting. I think all the races are fixed now -- I had to redesign the guts of the library to fix them. I may have introduced other issues in the process.
